export { ReactComponent as Crypto } from "./Crypto.svg"
export { ReactComponent as MysteryCube } from "./MysteryCube.svg"
export { ReactComponent as Overview } from "./Overview.svg"
export { ReactComponent as Quote } from "./Quote.svg"
export { ReactComponent as Radio } from "./Radio.svg"
export { ReactComponent as Til } from "./Til.svg"
export { ReactComponent as Timer } from "./Timer.svg"
export { ReactComponent as Tv } from "./Tv.svg"
