import type { FC, SVGProps } from "react"

type Icon = FC<SVGProps<SVGSVGElement>>

export const Apps: Icon
export const Art: Icon
export const BookmarkDefault: Icon
export const BookmarkSaved: Icon
export const Design: Icon
export const Dev: Icon
export const Discord: Icon
export const DownArrow: Icon
export const Drag: Icon
export const Dropdown: Icon
export const Email: Icon
export const Europe: Icon
export const Favorite: Icon
export const FolderFilled: Icon
export const FolderUnfilled: Icon
export const Gaming: Icon
export const Home: Icon
export const Hookito: Icon
export const HookitoFull: Icon
export const Images: Icon
export const Insight: Icon
export const Learn: Icon
export const Liked: Icon
export const Link: Icon
export const Live: Icon
export const Loading: Icon
export const Lock: Icon
export const Maps: Icon
export const Marketing: Icon
export const Moon: Icon
export const Move: Icon
export const Music: Icon
export const News: Icon
export const Next: Icon
export const Pause: Icon
export const Play: Icon
export const Podcast: Icon
export const Present: Icon
export const Previous: Icon
export const Question: Icon
export const Radio: Icon
export const Rain: Icon
export const RSS: Icon
export const Search: Icon
export const Seat: Icon
export const Share: Icon
export const Shopping: Icon
export const Startpage: Icon
export const Stocks: Icon
export const Sun: Icon
export const Throw: Icon
export const Thunder: Icon
export const Tree: Icon
export const Unlock: Icon
export const Uparrow: Icon
export const Volume: Icon
export const WWW: Icon
